
"use client";

import React, { createContext, useState, useContext, ReactNode } from 'react';

const translations = {
  en: {
    features: "Features",
    about: "About",
    reviews: "Reviews",
    contact: "Contact",
    login: "Login",
    selectLanguage: "Select language",
    language: "Language",
    heroTitle: "Streamline Your Restaurant Operations",
    heroSubtitle: "CuisineFlow is the all-in-one platform to manage bookings, tables, customers, and analytics, all in one place.",
    discoverFeatures: "Discover Features",
    featuresTitle: "Everything You Need to Succeed",
    feature1Title: "Effortless Booking Management",
    feature1Desc: "Handle all your reservations from one simple, powerful interface. Add, edit, and track bookings with ease.",
    feature2Title: "Visual Table Management",
    feature2Desc: "Get a real-time overview of your restaurant floor. Assign tables, track status, and optimize seating.",
    feature3Title: "Customer Relationship Hub",
    feature3Desc: "Keep track of your guests and their preferences to provide personalized service and build loyalty.",
    feature4Title: "In-Depth Analytics",
    feature4Desc: "Make informed decisions with detailed reports on bookings, revenue, and customer trends.",
    aboutTitle: "Designed for Growth",
    benefit1Title: "For Your Team",
    benefit1Desc: "Empower your staff with intuitive tools that reduce manual work and let them focus on providing excellent service.",
    benefit2Title: "For Your Business",
    benefit2Desc: "Gain valuable insights with powerful analytics, helping you make data-driven decisions to boost profitability.",
    benefit3Title: "For Your Guests",
    benefit3Desc: "Ensure a seamless dining experience from booking to billing, increasing customer satisfaction and loyalty.",
    testimonialsTitle: "Words from Our Guests",
    testimonial1: "CuisineFlow has revolutionized how we manage our floor. The real-time table view is a game changer for our host team!",
    testimonial2: "The analytics are incredibly powerful. We've been able to optimize our peak hours and increase revenue by 20%!",
    testimonial3: "Our repeat customer rate has gone up since we started using the CRM features. Guests love the personalized service.",
    testimonial4: "As a manager, I can't imagine running the restaurant without CuisineFlow. It simplifies everything from bookings to reports.",
    contactTitle: "Get in Touch",
    contactFormName: "Name",
    contactFormEmail: "Email",
    contactFormMessage: "Message",
    contactFormMessagePlaceholder: "Tell us how we can help",
    contactFormSubmit: "Send Message",
    contactFormSuccessTitle: "Message Sent!",
    contactFormSuccessDesc: "Thanks for reaching out. We'll get back to you soon.",
    dashboard: "Dashboard",
    bookings: "Bookings",
    tables: "Tables",
    customers: "Customers",
    analytics: "Analytics",
    upgradeToPro: "Upgrade to Pro",
    upgradeToProDesc: "Unlock all features and get unlimited access to our support team.",
    upgrade: "Upgrade",
    toggleUserMenu: "Toggle user menu",
    myAccount: "My Account",
    settings: "Settings",
    support: "Support",
    logout: "Logout",
  },
  hi: {
    features: "विशेषताएँ",
    about: "हमारे बारे में",
    reviews: "समीक्षाएँ",
    contact: "संपर्क करें",
    login: "लॉग इन करें",
    selectLanguage: "भाषा चुनें",
    language: "भाषा",
    heroTitle: "अपने रेस्तरां के संचालन को सुव्यवस्थित करें",
    heroSubtitle: "CuisineFlow बुकिंग, टेबल, ग्राहक और एनालिटिक्स को एक ही स्थान पर प्रबंधित करने का एक मंच है।",
    discoverFeatures: "विशेषताएँ खोजें",
    featuresTitle: "सफलता के लिए आपको जो कुछ भी चाहिए",
    feature1Title: "सरल बुकिंग प्रबंधन",
    feature1Desc: "एक सरल, शक्तिशाली इंटरफ़ेस से अपने सभी आरक्षणों को संभालें। आसानी से बुकिंग जोड़ें, संपादित करें और ट्रैक करें।",
    feature2Title: "विज़ुअल टेबल प्रबंधन",
    feature2Desc: "अपने रेस्तरां के फ्लोर का वास्तविक समय अवलोकन प्राप्त करें। टेबल असाइन करें, स्थिति ट्रैक करें और बैठने की व्यवस्था को अनुकूलित करें।",
    feature3Title: "ग्राहक संबंध हब",
    feature3Desc: "व्यक्तिगत सेवा प्रदान करने और वफादारी बनाने के लिए अपने मेहमानों और उनकी प्राथमिकताओं पर नज़र रखें।",
    feature4Title: "गहन विश्लेषण",
    feature4Desc: "बुकिंग, राजस्व और ग्राहक प्रवृत्तियों पर विस्तृत रिपोर्ट के साथ सूचित निर्णय लें।",
    aboutTitle: "विकास के लिए डिज़ाइन किया गया",
    benefit1Title: "आपकी टीम के लिए",
    benefit1Desc: "अपने कर्मचारियों को सहज उपकरणों से सशक्त बनाएं जो मैन्युअल काम को कम करते हैं और उन्हें उत्कृष्ट सेवा प्रदान करने पर ध्यान केंद्रित करने देते हैं।",
    benefit2Title: "आपके व्यवसाय के लिए",
    benefit2Desc: "शक्तिशाली एनालिटिक्स के साथ मूल्यवान अंतर्दृष्टि प्राप्त करें, जो आपको लाभप्रदता बढ़ाने के लिए डेटा-संचालित निर्णय लेने में मदद करता है।",
    benefit3Title: "आपके मेहमानों के लिए",
    benefit3Desc: "बुकिंग से लेकर बिलिंग तक एक सहज भोजन अनुभव सुनिश्चित करें, जिससे ग्राहकों की संतुष्टि और वफादारी बढ़ती है।",
    testimonialsTitle: "हमारे मेहमानों के शब्द",
    testimonial1: "CuisineFlow ने हमारे फ्लोर के प्रबंधन के तरीके में क्रांति ला दी है। रियल-टाइम टेबल व्यू हमारी होस्ट टीम के लिए एक गेम चेंजर है!",
    testimonial2: "एनालिटिक्स अविश्वसनीय रूप से शक्तिशाली हैं। हम अपने पीक आवर्स को ऑप्टिमाइज़ करने और राजस्व में 20% की वृद्धि करने में सक्षम हुए हैं!",
    testimonial3: "जब से हमने CRM सुविधाओं का उपयोग करना शुरू किया है, तब से हमारी रिपीट ग्राहक दर बढ़ गई है। मेहमानों को व्यक्तिगत सेवा पसंद है।",
    testimonial4: "एक प्रबंधक के रूप में, मैं CuisineFlow के बिना रेस्तरां चलाने की कल्पना नहीं कर सकता। यह बुकिंग से लेकर रिपोर्ट तक सब कुछ सरल करता है।",
    contactTitle: "संपर्क में रहें",
    contactFormName: "नाम",
    contactFormEmail: "ईमेल",
    contactFormMessage: "संदेश",
    contactFormMessagePlaceholder: "बताएं कि हम कैसे मदद कर सकते हैं",
    contactFormSubmit: "संदेश भेजें",
    contactFormSuccessTitle: "संदेश भेजा गया!",
    contactFormSuccessDesc: "संपर्क करने के लिए धन्यवाद। हम जल्द ही आपसे संपर्क करेंगे।",
    dashboard: "डैशबोर्ड",
    bookings: "बुकिंग",
    tables: "टेबल",
    customers: "ग्राहक",
    analytics: "एनालिटिक्स",
    upgradeToPro: "प्रो में अपग्रेड करें",
    upgradeToProDesc: "सभी सुविधाओं को अनलॉक करें और हमारी सहायता टीम तक असीमित पहुंच प्राप्त करें।",
    upgrade: "अपग्रेड",
    toggleUserMenu: "उपयोगकर्ता मेनू टॉगल करें",
    myAccount: "मेरा खाता",
    settings: "सेटिंग्स",
    support: "सहायता",
    logout: "लॉग आउट",
  },
  kn: {
    features: "ವೈಶಿಷ್ಟ್ಯಗಳು",
    about: "ನಮ್ಮ ಬಗ್ಗೆ",
    reviews: "ವಿಮರ್ಶೆಗಳು",
    contact: "ಸಂಪರ್ಕಿಸಿ",
    login: "ಲಾಗಿನ್ ಮಾಡಿ",
    selectLanguage: "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    language: "ಭಾಷೆ",
    heroTitle: "ನಿಮ್ಮ ರೆಸ್ಟೋರೆಂಟ್ ಕಾರ್ಯಾಚರಣೆಗಳನ್ನು सुव्यवस्थितಗೊಳಿಸಿ",
    heroSubtitle: "CuisineFlow ಬುಕಿಂಗ್‌ಗಳು, ಟೇಬಲ್‌ಗಳು, ಗ್ರಾಹಕರು ಮತ್ತು ವಿಶ್ಲೇಷಣೆಗಳನ್ನು ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ ನಿರ್ವಹಿಸಲು ಒಂದು ವೇದಿಕೆಯಾಗಿದೆ.",
    discoverFeatures: "ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ಅನ್ವೇಷಿಸಿ",
    featuresTitle: "ಯಶಸ್ಸಿಗೆ ನಿಮಗೆ ಬೇಕಾದ ಎಲ್ಲವೂ",
    feature1Title: "ಸರಳ ಬುಕಿಂಗ್ ನಿರ್ವಹಣೆ",
    feature1Desc: "ಒಂದು ಸರಳ, ಶಕ್ತಿಯುತ ಇಂಟರ್ಫೇಸ್‌ನಿಂದ ನಿಮ್ಮ ಎಲ್ಲಾ ಕಾಯ್ದಿರಿಸುವಿಕೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ. ಸುಲಭವಾಗಿ ಬುಕಿಂಗ್‌ಗಳನ್ನು ಸೇರಿಸಿ, ಸಂಪಾದಿಸಿ ಮತ್ತು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.",
    feature2Title: "ದೃಶ್ಯ ಟೇಬಲ್ ನಿರ್ವಹಣೆ",
    feature2Desc: "ನಿಮ್ಮ ರೆಸ್ಟೋರೆಂಟ್ ಮಹಡಿಯ ನೈಜ-ಸಮಯದ ಅವಲೋಕನವನ್ನು ಪಡೆಯಿರಿ. ಟೇಬಲ್‌ಗಳನ್ನು ನಿಯೋಜಿಸಿ, ಸ್ಥಿತಿಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ಆಸನವನ್ನು ಅತ್ಯುತ್ತಮವಾಗಿಸಿ.",
    feature3Title: "ಗ್ರಾಹಕ ಸಂಬಂಧ ಕೇಂದ್ರ",
    feature3Desc: "ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ಸೇವೆಯನ್ನು ಒದಗಿಸಲು ಮತ್ತು ನಿಷ್ಠೆಯನ್ನು வளர்த்தಿಕೊಳ್ಳಲು ನಿಮ್ಮ ಅತಿಥಿಗಳು ಮತ್ತು ಅವರ ಆದ್ಯತೆಗಳನ್ನು ಗಮನದಲ್ಲಿಟ್ಟುಕೊಳ್ಳಿ.",
    feature4Title: "ಆಳವಾದ ವಿಶ್ಲೇಷಣೆಗಳು",
    feature4Desc: "ಬುಕಿಂಗ್‌ಗಳು, ಆದಾಯ ಮತ್ತು ಗ್ರಾಹಕರ ಪ್ರವೃತ್ತಿಗಳ ಬಗ್ಗೆ ವಿವರವಾದ ವರದಿಗಳೊಂದಿಗೆ ತಿಳುವಳಿಕೆಯುಳ್ಳ ನಿರ್ಧಾರಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಿ.",
    aboutTitle: "ಬೆಳವಣಿಗೆಗಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ",
    benefit1Title: "ನಿಮ್ಮ ತಂಡಕ್ಕಾಗಿ",
    benefit1Desc: "ಕೈಯಿಂದ ಮಾಡುವ ಕೆಲಸವನ್ನು ಕಡಿಮೆ ಮಾಡುವ ಮತ್ತು ಅತ್ಯುತ್ತಮ ಸೇವೆಯನ್ನು ಒದಗಿಸುವುದರ ಮೇಲೆ ಗಮನಹರಿಸಲು ಅನುವು ಮಾಡಿಕೊಡುವ ಅರ್ಥಗರ್ಭಿತ ಸಾಧನಗಳೊಂದಿಗೆ ನಿಮ್ಮ ಸಿಬ್ಬಂದಿಯನ್ನು ಸಶಕ್ತಗೊಳಿಸಿ.",
    benefit2Title: "ನಿಮ್ಮ ವ್ಯಾಪಾರಕ್ಕಾಗಿ",
    benefit2Desc: "ಪ್ರಬಲ ವಿಶ್ಲೇಷಣೆಗಳೊಂದಿಗೆ ಅಮೂಲ್ಯವಾದ ಒಳನೋಟಗಳನ್ನು ಪಡೆಯಿರಿ, ಲಾಭದಾಯಕತೆಯನ್ನು ಹೆಚ್ಚಿಸಲು ಡೇಟಾ-ಚಾಲಿತ ನಿರ್ಧಾರಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಲು ನಿಮಗೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
    benefit3Title: "ನಿಮ್ಮ ಅತಿಥಿಗಳಿಗಾಗಿ",
    benefit3Desc: "ಬುಕಿಂಗ್‌ನಿಂದ ಬಿಲ್ಲಿಂಗ್‌ವರೆಗೆ ತಡೆರಹಿತ ಊಟದ ಅನುಭವವನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ, ಗ್ರಾಹಕರ সন্তುষ্টি ಮತ್ತು ನಿಷ್ಠೆಯನ್ನು ಹೆಚ್ಚಿಸುತ್ತದೆ.",
    testimonialsTitle: "ನಮ್ಮ ಅತಿಥಿಗಳ ಮಾತುಗಳು",
    testimonial1: "CuisineFlow ನಾವು ನಮ್ಮ ಮಹಡಿಯನ್ನು ನಿರ್ವಹಿಸುವ രീതിಯಲ್ಲಿ ಕ್ರಾಂತಿಯನ್ನುಂಟುಮಾಡಿದೆ. ನೈಜ-ಸಮಯದ ಟೇಬಲ್ ವೀಕ್ಷಣೆ ನಮ್ಮ ಹೋസ്റ്റ് ತಂಡಕ್ಕೆ ಒಂದು ಗೇಮ್ ಚೇಂಜರ್ ಆಗಿದೆ!",
    testimonial2: "ವಿಶ್ಲೇಷಣೆಗಳು അവിശ്വസನೀಯವಾಗಿ ಶಕ್ತಿಯುತವಾಗಿವೆ. ನಾವು ನಮ್ಮ ಗರಿಷ್ಠ ಗಂಟೆಗಳನ್ನು ಅತ್ಯುತ್ತಮವಾಗಿಸಲು ಮತ್ತು ಆದಾಯವನ್ನು 20% ಹೆಚ್ಚಿಸಲು ಸಾಧ್ಯವಾಯಿತು!",
    testimonial3: "ನಾವು CRM ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ಬಳಸಲು ಪ್ರಾರಂಭಿಸಿದಾಗಿನಿಂದ ನಮ್ಮ ಪುನರಾವರ್ತಿತ ಗ್ರಾಹಕರ ದರ ಹೆಚ್ಚಾಗಿದೆ. ಅತಿಥಿಗಳು ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ಸೇವೆಯನ್ನು ಇಷ್ಟಪಡುತ್ತಾರೆ.",
    testimonial4: "ಒಬ್ಬ ಮ್ಯಾನೇಜರ್ ಆಗಿ, CuisineFlow ಇಲ್ಲದೆ ರೆಸ್ಟೋರೆಂಟ್ ನಡೆಸುವುದನ್ನು আমি ಊಹಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ. ಇದು ಬುಕಿಂಗ್‌ನಿಂದ ವರದಿಗಳವರೆಗೆ ಎಲ್ಲವನ್ನೂ ಸರಳಗೊಳಿಸುತ್ತದೆ.",
    contactTitle: "ಸಂಪರ್ಕದಲ್ಲಿರಿ",
    contactFormName: "ಹೆಸರು",
    contactFormEmail: "ಇಮೇಲ್",
    contactFormMessage: "ಸಂದೇಶ",
    contactFormMessagePlaceholder: "ನಾವು ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು ಎಂದು ನಮಗೆ ತಿಳಿಸಿ",
    contactFormSubmit: "ಸಂದೇಶ ಕಳುಹಿಸಿ",
    contactFormSuccessTitle: "ಸಂದೇಶ ಕಳುಹಿಸಲಾಗಿದೆ!",
    contactFormSuccessDesc: "ತಲುಪಿದ್ದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು. ನಾವು ಶೀಘ್ರದಲ್ಲೇ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತೇವೆ.",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    bookings: "ಬುಕಿಂಗ್‌ಗಳು",
    tables: "ಟೇಬಲ್‌ಗಳು",
    customers: "ಗ್ರಾಹಕರು",
    analytics: "ವಿಶ್ಲೇಷಣೆಗಳು",
    upgradeToPro: "ಪ್ರೊಗೆ ಅಪ್‌ಗ್ರೇಡ್ ಮಾಡಿ",
    upgradeToProDesc: "ಎಲ್ಲಾ ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ಅನ್‌ಲಾಕ್ ಮಾಡಿ ಮತ್ತು ನಮ್ಮ ಬೆಂಬಲ ತಂಡಕ್ಕೆ ಅನಿಯಮಿತ ಪ್ರವೇಶವನ್ನು ಪಡೆಯಿರಿ.",
    upgrade: "ಅಪ್‌ಗ್ರೇಡ್",
    toggleUserMenu: "ಬಳಕೆದಾರರ ಮೆನು ಟಾಗಲ್ ಮಾಡಿ",
    myAccount: "ನನ್ನ ಖಾತೆ",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    support: "ಬೆಂಬಲ",
    logout: "ಲಾಗ್ ಔಟ್",
  },
  te: {
    features: "ఫీచర్లు",
    about: "మా గురించి",
    reviews: "సमीక్షలు",
    contact: "సంప్రదించండి",
    login: "లాగిన్",
    selectLanguage: "భాషను ఎంచుకోండి",
    language: "భాష",
    heroTitle: "మీ రెస్టారెంట్ కార్యకలాపాలను సులభతరం చేయండి",
    heroSubtitle: "CuisineFlow బుకింగ్‌లు, టేబుల్స్, కస్టమర్‌లు మరియు అనలిటిక్స్‌ను ఒకే చోట నిర్వహించడానికి ఒక వేదిక.",
    discoverFeatures: "ఫీచర్లను కనుగొనండి",
    featuresTitle: "విజయం కోసం మీకు కావలసినవన్నీ",
    feature1Title: "సులభమైన బుకింగ్ నిర్వహణ",
    feature1Desc: "ఒక సాధారణ, శక్తివంతమైన ఇంటర్‌ఫేస్ నుండి మీ అన్ని రిజర్వేషన్‌లను నిర్వహించండి. బుకింగ్‌లను సులభంగా జోడించండి, సవరించండి మరియు ట్రాక్ చేయండి.",
    feature2Title: "విజువల్ టేబుల్ నిర్వహణ",
    feature2Desc: "మీ రెస్టారెంట్ ఫ్లోర్ యొక్క నిజ-సమయ అవలోకనాన్ని పొందండి. టేబుల్స్‌ను కేటాయించండి, స్థితిని ట్రాక్ చేయండి మరియు సీటింగ్‌ను ఆప్టిమైజ్ చేయండి.",
    feature3Title: "కస్టమర్ రిలేషన్‌షిప్ హబ్",
    feature3Desc: "వ్యక్తిగతీకరించిన సేవను అందించడానికి మరియు విశ్వసనీయతను పెంచుకోవడానికి మీ అతిథులు మరియు వారి ప్రాధాన్యతలను ట్రాక్ చేయండి.",
    feature4Title: "లోతైన అనలిటిక్స్",
    feature4Desc: "బుకింగ్‌లు, రాబడి మరియు కస్టమర్ ట్రెండ్‌లపై వివరణాత్మక నివేదికలతో సమాచారంతో కూడిన నిర్ణయాలు తీసుకోండి.",
    aboutTitle: "అభివృద్ధి కోసం రూపొందించబడింది",
    benefit1Title: "మీ బృందం కోసం",
    benefit1Desc: "మీ సిబ్బందికి మాన్యువల్ పనిని తగ్గించే మరియు అద్భుతమైన సేవను అందించడంపై దృష్టి పెట్టడానికి వీలు కల్పించే సహజమైన సాధనాలతో సాధికారత కల్పించండి.",
    benefit2Title: "మీ వ్యాపారం కోసం",
    benefit2Desc: "శక్తివంతమైన అనలిటిక్స్‌తో విలువైన అంతర్దృష్టులను పొందండి, లాభదాయకతను పెంచడానికి డేటా-ఆధారిత నిర్ణయాలు తీసుకోవడంలో మీకు సహాయపడుతుంది.",
    benefit3Title: "మీ అతిథుల కోసం",
    benefit3Desc: "బుకింగ్ నుండి బిల్లింగ్ వరకు అతుకులు లేని భోజన అనుభవాన్ని నిర్ధారించండి, కస్టమర్ సంతృప్తి మరియు విశ్వసనీయతను పెంచుతుంది.",
    testimonialsTitle: "మా అతిథుల మాటలు",
    testimonial1: "CuisineFlow మేము మా ఫ్లోర్‌ను నిర్వహించే విధానంలో విప్లవాత్మక మార్పులు చేసింది. నిజ-సమయ టేబుల్ వీక్షణ మా హోస్ట్ బృందానికి ఒక గేమ్ ఛేంజర్!",
    testimonial2: "అనలిటిక్స్ అద్భుతంగా శక్తివంతమైనవి. మేము మా గరిష్ట గంటలను ఆప్టిమైజ్ చేయడానికి మరియు రాబడిని 20% పెంచడానికి ಸಾಧ್ಯమైంది!",
    testimonial3: "మేము CRM ఫీచర్లను ఉపయోగించడం ప్రారంభించినప్పటి నుండి మా పునరావృత కస్టమర్ రేటు పెరిగింది. అతిథులు వ్యక్తిగతీకరించిన సేవను ఇష్టపడతారు.",
    testimonial4: "ఒక మేనేజర్‌గా, CuisineFlow లేకుండా రెస్టారెంట్‌ను నడపడాన్ని ನಾನು ఊహించలేను. ఇది బుకింగ్‌ల నుండి నివేదికల వరకు ప్రతిదీ సులభతరం చేస్తుంది.",
    contactTitle: "సంప్రదింపు nawaru",
    contactFormName: "పేరు",
    contactFormEmail: "ఇమెయిల్",
    contactFormMessage: "సందేశం",
    contactFormMessagePlaceholder: "మేము ఎలా సహాయపడగలమో మాకు చెప్పండి",
    contactFormSubmit: "సందేశం పంపండి",
    contactFormSuccessTitle: "సందేశం పంపబడింది!",
    contactFormSuccessDesc: "సంప్రదించినందుకు ధన్యవాదాలు. మేము త్వరలో మిమ్మల్ని సంప్రదిస్తాము.",
    dashboard: "డాష్‌బోర్డ్",
    bookings: "బుకింగ్‌లు",
    tables: "టేబుల్స్",
    customers: "కస్టమర్‌లు",
    analytics: "అనలిటిక్స్",
    upgradeToPro: "ప్రోకి అప్‌గ్రేడ్ చేయండి",
    upgradeToProDesc: "అన్ని ఫీచర్లను అన్‌లాక్ చేయండి మరియు మా మద్దతు బృందానికి అపరిమిత ప్రాప్యతను పొందండి.",
    upgrade: "అప్‌గ్రేడ్",
    toggleUserMenu: "వినియోగదారు మెనుని టోగుల్ చేయండి",
    myAccount: "నా ఖాతా",
    settings: "సెట్టింగ్‌లు",
    support: "మద్దతు",
    logout: "లాగ్ అవుట్",
  },
  ta: {
    features: "அம்சங்கள்",
    about: "எங்களைப் பற்றி",
    reviews: "விமர்சனங்கள்",
    contact: "தொடர்பு",
    login: "உள்நுழை",
    selectLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்",
    language: "மொழி",
    heroTitle: "உங்கள் உணவக செயல்பாடுகளை सुव्यवस्थितப்படுத்துங்கள்",
    heroSubtitle: "CuisineFlow முன்பதிவுகள், அட்டவணைகள், வாடிக்கையாளர்கள் மற்றும் பகுப்பாய்வுகளை ಒಂದே இடத்தில் நிர்வகிப்பதற்கான ஒரு தளமாகும்.",
    discoverFeatures: "அம்சங்களைக் கண்டறியவும்",
    featuresTitle: "வெற்றிக்கு உங்களுக்குத் தேவையான அனைத்தும்",
    feature1Title: "எளிதான முன்பதிவு மேலாண்மை",
    feature1Desc: "ஒரு எளிய, சக்திவாய்ந்த இடைமுகத்திலிருந்து உங்கள் அனைத்து முன்பதிவுகளையும் கையாளவும். முன்பதிவுகளை எளிதாகச் சேர்க்கவும், திருத்தவும் மற்றும் கண்காணிக்கவும்.",
    feature2Title: "காட்சி அட்டவணை மேலாண்மை",
    feature2Desc: "உங்கள் உணவகத் தளத்தின் நிகழ்நேர கண்ணோட்டத்தைப் பெறுங்கள். அட்டவணைகளை ஒதுக்குங்கள், நிலையைக் கண்காணிக்கவும் மற்றும் இருக்கையை மேம்படுத்தவும்.",
    feature3Title: "வாடிக்கையாளர் உறவு மையம்",
    feature3Desc: "தனிப்பயனாக்கப்பட்ட சேவையை வழங்கவும், விசுவாசத்தை வளர்க்கவும் உங்கள் விருந்தினர்கள் மற்றும் அவர்களின் விருப்பங்களைக் கண்காணிக்கவும்.",
    feature4Title: "ஆழமான பகுப்பாய்வுகள்",
    feature4Desc: "முன்பதிவுகள், வருவாய் மற்றும் வாடிக்கையாளர் போக்குகள் குறித்த விரிவான அறிக்கைகளுடன் தகவலறிந்த முடிவுகளை எடுக்கவும்.",
    aboutTitle: "வளர்ச்சிக்காக வடிவமைக்கப்பட்டது",
    benefit1Title: "உங்கள் குழுவிற்கு",
    benefit1Desc: "கையேடு வேலையைக் குறைக்கும் மற்றும் சிறந்த சேவையை வழங்குவதில் கவனம் செலுத்த அனுமதிக்கும் உள்ளுணர்வு கருவிகளைக் கொண்டு உங்கள் ஊழியர்களுக்கு அதிகாரம் அளியுங்கள்.",
    benefit2Title: "உங்கள் வணிகத்திற்கு",
    benefit2Desc: "சக்திவாய்ந்த பகுப்பாய்வுகளுடன் மதிப்புமிக்க நுண்ணறிவுகளைப் பெறுங்கள், லாபத்தை அதிகரிக்க தரவு சார்ந்த முடிவுகளை எடுக்க உதவுகிறது.",
    benefit3Title: "உங்கள் விருந்தினர்களுக்கு",
    benefit3Desc: "முன்பதிவு முதல் பில்லிங் வரை தடையற்ற உணவு அனுபவத்தை உறுதிசெய்து, வாடிக்கையாளர் திருப்தி மற்றும் விசுவாசத்தை அதிகரிக்கும்.",
    testimonialsTitle: "எங்கள் விருந்தினர்களின் வார்த்தைகள்",
    testimonial1: "CuisineFlow நாங்கள் எங்கள் தளத்தை நிர்வகிக்கும் விதத்தில் புரட்சியை ஏற்படுத்தியுள்ளது. நிகழ்நேர அட்டவணை பார்வை எங்கள் புரவலர் குழுவிற்கு ஒரு கேம் சேஞ்சர்!",
    testimonial2: "பகுப்பாய்வுகள் நம்பமுடியாத அளவிற்கு சக்திவாய்ந்தவை. நாங்கள் எங்கள் உச்ச நேரங்களை மேம்படுத்தவும், வருவாயை 20% அதிகரிக்கவும் முடிந்தது!",
    testimonial3: "நாங்கள் CRM அம்சங்களைப் பயன்படுத்தத் தொடங்கியதிலிருந்து எங்கள் மீண்டும் வரும் வாடிக்கையாளர் விகிதம் அதிகரித்துள்ளது. விருந்தினர்கள் தனிப்பயனாக்கப்பட்ட சேவையை விரும்புகிறார்கள்.",
    testimonial4: "ഒരു മാനേജർ എന്ന നിലയിൽ, CuisineFlow ഇല്ലാതെ റെസ്റ്റോറന്റ് നടത്തുന്നത് എനിക്ക് സങ്കൽപ്പിക്കാൻ കഴിയില്ല. ഇത് ബുക്കിംഗ് മുതൽ റിപ്പോർട്ടുകൾ വരെ എല്ലാം ലളിതമാക്കുന്നു.",
    contactTitle: "தொடர்பில் இருங்கள்",
    contactFormName: "பெயர்",
    contactFormEmail: "மின்னஞ்சல்",
    contactFormMessage: "செய்தி",
    contactFormMessagePlaceholder: "நாங்கள் எப்படி உதவ முடியும் என்று எங்களிடம் கூறுங்கள்",
    contactFormSubmit: "செய்தியை அனுப்பு",
    contactFormSuccessTitle: "செய்தி அனுப்பப்பட்டது!",
    contactFormSuccessDesc: "தொடர்பு கொண்டதற்கு நன்றி. நாங்கள் விரைவில் உங்களைத் தொடர்புகொள்வோம்.",
    dashboard: "డాష్‌బోర్డ్",
    bookings: "முன்பதிவுகள்",
    tables: "அட்டவணைகள்",
    customers: "வாடிக்கையாளர்கள்",
    analytics: "பகுப்பாய்வுகள்",
    upgradeToPro: "ப்ரோకు மேம்படுத்தவும்",
    upgradeToProDesc: "அனைத்து அம்சங்களையும் திறக்கவும், எங்கள் ஆதரவுக் குழுவிற்கு வரம்பற்ற அணுகலைப் பெறவும்.",
    upgrade: "மேம்படுத்து",
    toggleUserMenu: "பயனர் மெனுவை மாற்று",
    myAccount: "என் கணக்கு",
    settings: "அமைப்புகள்",
    support: "ஆதரவு",
    logout: "வெளியேறு",
  },
  ml: {
    features: "ഫീച്ചറുകൾ",
    about: "ഞങ്ങളെക്കുറിച്ച്",
    reviews: "അവലോകനങ്ങൾ",
    contact: "ബന്ധപ്പെടുക",
    login: "ലോഗിൻ ചെയ്യുക",
    selectLanguage: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    language: "ഭാഷ",
    heroTitle: "നിങ്ങളുടെ റെസ്റ്റോറന്റ് പ്രവർത്തനങ്ങൾ കാര്യക്ഷമമാക്കുക",
    heroSubtitle: "ബുക്കിംഗുകൾ, ടേബിളുകൾ, ഉപഭോക്താക്കൾ, അനലിറ്റിക്സ് എന്നിവയെല്ലാം ഒരിടത്ത് ನಿರ್ವಹിക്കാനുള്ള ഒരു വേദിയാണ് CuisineFlow.",
    discoverFeatures: "ഫീച്ചറുകൾ കണ്ടെത്തുക",
    featuresTitle: "വിജയത്തിന് നിങ്ങൾക്ക് 필요한തെല്ലാം",
    feature1Title: "പ്രയാസമില്ലാത്ത ബുക്കിംഗ് മാനേജ്മെന്റ്",
    feature1Desc: "ഒരു ലളിതവും ശക്തവുമായ ഇന്റർഫേസിൽ നിന്ന് നിങ്ങളുടെ എല്ലാ റിസർവേഷനുകളും കൈകാര്യം ചെയ്യുക. ബുക്കിംഗുകൾ എളുപ്പത്തിൽ ചേർക്കുക, എഡിറ്റുചെയ്യുക, ട്രാക്ക് ചെയ്യുക.",
    feature2Title: "വിഷ്വൽ ടേബിൾ മാനേജ്മെന്റ്",
    feature2Desc: "നിങ്ങളുടെ റെസ്റ്റോറന്റ് ഫ്ലോറിന്റെ തത്സമയ അവലോകനം നേടുക. ടേബിളുകൾ നൽകുക, സ്റ്റാറ്റസ് ട്രാക്ക് ചെയ്യുക, ഇരിപ്പിടം ഒപ്റ്റിമൈസ് ചെയ്യുക.",
    feature3Title: "ഉപഭോക്തൃ ബന്ധ കേന്ദ്രം",
    feature3Desc: "വ്യക്തിഗത സേവനം നൽകുന്നതിനും విశ్వস্তത വളർത്തുന്നതിനും നിങ്ങളുടെ അതിഥികളെയും അവരുടെ മുൻഗണനകളെയും ട്രാക്ക് ചെയ്യുക.",
    feature4Title: "ആഴത്തിലുള്ള അനലിറ്റിക്സ്",
    feature4Desc: "ബുക്കിംഗുകൾ, വരുമാനം, ഉപഭോക്തൃ പ്രവണതകൾ എന്നിവയെക്കുറിച്ചുള്ള വിശദമായ റിപ്പോർട്ടുകൾ ഉപയോഗിച്ച് അറിവോടെയുള്ള തീരുമാനങ്ങൾ എടുക്കുക.",
    aboutTitle: "വളർച്ചയ്ക്കായി രൂപകൽപ്പന ചെയ്തിരിക്കുന്നു",
    benefit1Title: "നിങ്ങളുടെ ടീമിനായി",
    benefit1Desc: "മാനുവൽ ജോലി കുറയ്ക്കുകയും മികച്ച സേവനം നൽകുന്നതിൽ ശ്രദ്ധ കേന്ദ്രീകരിക്കാൻ അനുവദിക്കുകയും ചെയ്യുന്ന അവബോധജന്യമായ ഉപകരണങ്ങൾ ഉപയോഗിച്ച് നിങ്ങളുടെ സ്റ്റാഫിനെ ശാക്തീകരിക്കുക.",
    benefit2Title: "നിങ്ങളുടെ ബിസിനസ്സിനായി",
    benefit2Desc: " ശക്തമായ അനലിറ്റിക്സ് ഉപയോഗിച്ച് വിലയേറിയ ഉൾക്കാഴ്ചകൾ നേടുക, ലാഭക്ഷമത വർദ്ധിപ്പിക്കുന്നതിന് ഡാറ്റാധിഷ്ഠിത തീരുമാനങ്ങൾ എടുക്കാൻ നിങ്ങളെ സഹായിക്കുന്നു.",
    benefit3Title: "നിങ്ങളുടെ അതിഥികൾക്കായി",
    benefit3Desc: "ബുക്കിംഗ് മുതൽ ബില്ലിംഗ് വരെ തടസ്സമില്ലാത്ത ഭക്ഷണ അനുഭവം ഉറപ്പാക്കുക, ഉപഭോക്തൃ സംതൃപ്തിയും విశ్వস্তതയും വർദ്ധിപ്പിക്കുക.",
    testimonialsTitle: "ഞങ്ങളുടെ അതിഥികളുടെ വാക്കുകൾ",
    testimonial1: "CuisineFlow ഞങ്ങൾ ഞങ്ങളുടെ ഫ്ലോർ കൈകാര്യം ചെയ്യുന്ന രീതിയിൽ വിപ്ലവം സൃഷ്ടിച്ചു. തത്സമയ ടേബിൾ കാഴ്ച ഞങ്ങളുടെ ഹോസ്റ്റ് ടീമിന് ഒരു ഗെയിം ചേഞ്ചറാണ്!",
    testimonial2: "അനലിറ്റിക്സ് അവിശ്വസനീയമാംവിധം ശക്തമാണ്. ഞങ്ങൾക്ക് ഞങ്ങളുടെ പീക്ക് സമയങ്ങൾ ഒപ്റ്റിമൈസ് ചെയ്യാനും വരുമാനം 20% വർദ്ധിപ്പിക്കാനും കഴിഞ്ഞു!",
    testimonial3: "ഞങ്ങൾ CRM ഫീച്ചറുകൾ ഉപയോഗിക്കാൻ തുടങ്ങിയതുമുതൽ ഞങ്ങളുടെ ആവർത്തിച്ചുള്ള ഉപഭോക്തൃ നിരക്ക് വർദ്ധിച്ചു. അതിഥികൾ വ്യക്തിഗതമാക്കിയ സേവനം ഇഷ്ടപ്പെടുന്നു.",
    testimonial4: "ഒരു മാനേജർ എന്ന നിലയിൽ, CuisineFlow ഇല്ലാതെ റെസ്റ്റോറന്റ് നടത്തുന്നത് എനിക്ക് സങ്കൽപ്പിക്കാൻ കഴിയില്ല. ഇത് ബുക്കിംഗ് മുതൽ റിപ്പോർട്ടുകൾ വരെ എല്ലാം ലളിതമാക്കുന്നു.",
    contactTitle: "ബന്ധപ്പെടുക",
    contactFormName: "പേര്",
    contactFormEmail: "ഇമെയിൽ",
    contactFormMessage: "സന്ദേശം",
    contactFormMessagePlaceholder: "ഞങ്ങൾക്ക് എങ്ങനെ സഹായിക്കാനാകും എന്ന് പറയുക",
    contactFormSubmit: "സന്ദേശം അയയ്ക്കുക",
    contactFormSuccessTitle: "സന്ദേശം അയച്ചു!",
    contactFormSuccessDesc: "ബന്ധപ്പെട്ടതിന് നന്ദി. ഞങ്ങൾ ഉടൻ നിങ്ങളെ ബന്ധപ്പെടുന്നതാണ്.",
    dashboard: "ഡാഷ്ബോർഡ്",
    bookings: "ബുക്കിംഗുകൾ",
    tables: "ടേബിളുകൾ",
    customers: "ഉപഭോക്താക്കൾ",
    analytics: "അനലിറ്റിക്സ്",
    upgradeToPro: "പ്രോയിലേക്ക് അപ്‌ഗ്രേഡ് ചെയ്യുക",
    upgradeToProDesc: "എല്ലാ ഫീച്ചറുകളും അൺലോക്ക് ചെയ്യുകയും ഞങ്ങളുടെ സപ്പോർട്ട് ടീമിലേക്ക് പരിധിയില്ലാത്ത ആക്സസ് നേടുകയും ചെയ്യുക.",
    upgrade: "അപ്‌ഗ്രേഡ് ചെയ്യുക",
    toggleUserMenu: "ഉപയോക്തൃ മെനു ടോഗിൾ ചെയ്യുക",
    myAccount: "എന്റെ അക്കൗണ്ട്",
    settings: "ക്രമീകരണങ്ങൾ",
    support: "പിന്തുണ",
    logout: "ലോഗ് ഔട്ട്",
  }
};

type Translations = typeof translations.en;
type LanguageCode = keyof typeof translations;

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (language: LanguageCode) => void;
  t: (key: keyof Translations) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<LanguageCode>('en');

  const t = (key: keyof Translations) => {
    return translations[language][key] || translations.en[key];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
